name: Frontend deployment test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-deployment-test:

    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
  
      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Yarn setup
        run: |
          npm i -g yarn
        
      - name: Install Dependencies
        run: yarn

      - name: Hasura codegen
        run: |
          yarn codegen

      - name: eth_sdk codegen
        run: |
         yarn eth-sdk
         
      - name: eth_sdk codegen
        run: |
         yarn build

      
